config/routes.rb
Blog::Application.routes.draw do
  get "welcome/index"

  root 'welcome#index'

  resources :posts do
    resources :comments
    end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments
  validates :title, presence: true, length: { minimum: 5}
end

app/models/savjet.rb
class Savjet < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment].permit(:commenter, :body))
    redirect_to post_path(@post)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  private
  def post_params
    params.require(:post).permit(:title, :text)
  end

  public
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to @post
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post =Post.find(params[:id])

    if @post.update(post_params)
      redirect_to (@post)
    else
      render :edit
    end
  end

  def destroy
    @post =Post.find(params[:id])
    @post.destroy

    redirect_to posts_path
  end

  def show
    @post = Post.find(params[:id])
  end

  def index
    @posts = Post.all
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title Blog
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
    link rel="stylesheet" type="text/css" href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css"
  body
    == yield

app/views/posts/_form.html.slim
= form_for @post do |f|
  - if @post.errors.any?
    div#error_explanation
      h2 #{pluralize(@post.errors.count, "Error")} prohibited this post from being saved!
      ul
        - @post.errors.full_messages.each do |msg|
          li =msg
  p
    = f.label :title
    br
    = f.text_field :title
  p
    = f.label :text
    br
    = f.text_area :text
  p
    = f.submit

app/views/posts/edit.html.slim
h1 Editing Post
div.container
  =render 'form'
= link_to "Back", posts_path

app/views/posts/index.html.slim
h1 Listing posts
div class="container"
  p
    a href="posts/new" Create New Post
  table class="table table-striped"
    thead
      tr
        th Title
        th Text
        th Created At
        th
        th
        th
    - @posts.each do |post|
      tr
        td =post.title
        td =post.text
        td =post.created_at
        td =link_to "Show", post
        td =link_to 'Edit', edit_post_path(post)
        td =link_to 'Destroy', post_path(post), method: :delete, data: {confirm: "Are You Sure?"}

app/views/posts/new.html.slim
h1 New Post
div class="container"
  =render 'form'
  =link_to "Back", posts_path

app/views/posts/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @post.text %>
</p>
 
<h2>Add a comment:</h2>
<%= form_for([@post, @post.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br />
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>
 
<%= link_to 'Back', posts_path %>
| <%= link_to 'Edit', edit_post_path(@post) %>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @post.text %>
</p>

<h2>Comments</h2>
<% @post.comments.each do |comment| %>
    <p>
      <strong>Commenter:</strong>
      <%= comment.commenter %>
    </p>

    <p>
      <strong>Comment:</strong>
      <%= comment.body %>
    </p>
<% end %>

<h2>Add a comment:</h2>
<%= form_for([@post, @post.comments.build]) do |f| %>
    <p>
      <%= f.label :commenter %><br />
      <%= f.text_field :commenter %>
    </p>
    <p>
      <%= f.label :body %><br />
      <%= f.text_area :body %>
    </p>
    <p>
      <%= f.submit %>
    </p>
<% end %>

<%= link_to 'Edit Post', edit_post_path(@post) %> |
<%= link_to 'Back to Posts', posts_path %>

app/views/welcome/index.html.slim
h1 Hello, Rails!
div.container
  =link_to "My Blog", controller: "posts"